name: CI

on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - 'main'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Compile Translations
        run: yarn compile

      - name: Lint Types
        run: yarn lint:types

      - name: Lint Source
        run: yarn lint:source

      - name: Lint Formatting
        run: yarn lint:format
# TODO
#
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Read .nvmrc
#        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
#        id: nvm
#
#      - name: Setup Node.js ${{ steps.nvm.outputs.NVMRC }}
#        uses: actions/setup-node@v2.1.5
#        with:
#          node-version: ${{ steps.nvm.outputs.NVMRC }}
#
#      - name: Cache Dependencies
#        uses: actions/cache@v2.1.4
#        with:
#          path: node_modules
#          key: yarn-${{ hashFiles('yarn.lock') }}
#
#      - name: Install Dependencies
#        run: yarn install --frozen-lockfile --ignore-scripts
#
#      - name: Test
#        run: yarn test --coverage
#
#      - name: Upload Coverage
#        uses: codecov/codecov-action@v1
