name: Deployment

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            node_modules
            .cache
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Compile Translations
        run: yarn compile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
